### ISSUE TITLE
使用 less 的循环功能会报错

### ISSUE THREAD

**Issue by qyqwq** [vitejs/docs-cn#467]
使用以下代码时 会出现 `[plugin:vite:css] Operation on an invalid type`错误
```css
//依赖版本 "less": "^4.1.2",
.bar{
  position: relative;
  @itemWidth:100px;
  @iconWidth:45px;
  .pos-loop(@n, @i: 1) when(@i <= @n){
    &.pos@{i} {
      &::after{
        transform: translateX(@itemWidth*(@i - 1) + (@itemWidth - @iconWidth)/2);
      }
    }
    .pos-loop(@n, (@i + 1));
  }
  .pos-loop(3);
}
```
报错内容：
```
at less (D:\code\hdss-document\node_modules\vite\dist\node\chunks\dep-e1fc1d62.js:30694:33)
at async compileCSS (D:\code\hdss-document\node_modules\vite\dist\node\chunks\dep-e1fc1d62.js:30165:34)
at async TransformContext.transform (D:\code\hdss-document\node_modules\vite\dist\node\chunks\dep-e1fc1d62.js:29777:55)
at async Object.transform (D:\code\hdss-document\node_modules\vite\dist\node\chunks\dep-e1fc1d62.js:38961:30)
at async doTransform (D:\code\hdss-document\node_modules\vite\dist\node\chunks\dep-e1fc1d62.js:55918:29
```
![image](https://user-images.githubusercontent.com/45594375/168460428-eb5c5a31-f2ae-4214-8d1e-3b642b96d4c0.png)
